### ISSUE TITLE
get all repo details of user

### ISSUE THREAD

**Issue by PalaVenkiReddy** [Clueless-Community/scrape-up#159] opened 2023-03-09 10:51 UTC
### Description
returns all the details of each repo of given user.

### Example Usage

![image](https://user-images.githubusercontent.com/75984996/224002208-519d7212-2807-48b3-b6c7-a2551d0118c5.png)

```python

[
    {
        "name":"scrape-up",
        "link":"https://github.com/PalaVenkiReddy/scrape-up",
        "detail":"A web-scraping-based python package that enables you to scrape data from various platforms like GitHub, Twitter, Instagram, or any useful website.",
        "top_lang":"Python",
        "stars": ... ,
        "forks": ... ,
        "issues": ....,
        "pull requests" : ....,
    },
    ....
]
```

Please assign this issue to me under JWOC

**Comment by A15h** [comment] 2023-05-20 05:46
hi @nikhil25803  
I would really like to work on this issue . Please assign this issue to me. I am a contributor of GSSOC'23.

**Comment by urvi-swl** [comment] 2023-05-20 06:32
hi @nikhil25803 , I am a GSSoC'23 contributor and have been exploring scraping social media handles. So, it would be great if you assign this issue to me.

**Comment by nikhil25803** [comment] 2023-05-20 10:52
Sure @A15h, go ahead.

@urvi-swl  - As per the GSSoC'23 or any other open-source program format, it's the first come first assigned policy. Please try to look into other issues created, or feel free to create any.

**Comment by JammUtkarsh** [comment] 2023-05-20 13:27
@nikhil25803, even if the issue is not assigned to me, can I still make a PR?

**Comment by VardaPanchal005** [comment] 2023-05-20 16:11
I'm a GSSOC 23 contributor please assign me this issue

**Comment by nikhil25803** [comment] 2023-05-20 17:21
No @JammUtkarsh, you can not :((
and @VardaPanchal005 , this issue has already been assigned, please look for another one !!

**Comment by BabarRasheed** [comment] 2023-05-26 11:28
Hi,
I'm Babar Rasheed (Contributor GSSOC'23)
Many websites don't offer API so to tackle this we can use Web Scraping to access data in easy and structured manner.
Python libraries like bs4, BeautifulSoup, Scrapy, Selenium, etc. are generally used for web scraping.
Here I'm willing to apply these libraries and use an effective way of Multiprocessing to speed up Web Scraping.
Multiprocessing is very helpful when multiple URLs are scraped to get the data. It will perform scraping on multiple URLs thus saving our time.

**Comment by nikhil25803** [comment] 2023-06-08 19:26
Hey @A15h, any update?

**Comment by A15h** [comment] 2023-06-09 01:46
> Hey @A15h, any update?
hi @nikhil25803 
I am working on it. Please give me a day or two more.

**Comment by A15h** [comment] 2023-06-29 07:47
hi nikhil
I made the changes that you asked me to but you closed the issue. I want to
know was my pull request merged?

**Comment by A15h** [comment] 2023-06-29 07:52
This was the final file.

**Comment by nikhil25803** [comment] 2023-06-29 09:32
Hey @A15h | You closed the PR corresponding to this issue, that is why I closed it. If you want to raise an another PR for this file just reopen this issue.

**Comment by nikhil25803** [comment] 2023-06-29 09:36
Cool :))

**Closed** 2023-08-16 07:18 UTC
Labels: gssoc23
