### ISSUE TITLE
Add test files for Hashnode

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#854] opened 2023-12-05 10:21 UTC
**Note**
- Test all the methods of the `hashnode` module and add a test file.
- Add test file in directory `src/test`.
- Check the `hashnode.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by I-MirzaBaig** [comment] 2023-12-14 19:27
can i work on this under codepeak2023

**Comment by nikhil25803** [comment] 2023-12-14 20:15
Go ahead @I-MirzaBaig

**Comment by Dhruv127** [comment] 2023-12-19 10:21
kindly assign me the issue

**Comment by Vaibhav-Kumar10** [comment] 2024-05-10 05:40
If the issue is currently open, please assign this task to me under GSSoC'24.

**Comment by nikhil25803** [comment] 2024-05-10 14:45
Go ahead @Vaibhav-Kumar10

**Comment by hasmithagunda123** [comment] 2024-05-10 16:18
Hello I would like to work on this issue please assign it to me

**Comment by Vaibhav-Kumar10** [comment] 2024-05-10 18:47
> Go ahead @Vaibhav-Kumar10

Thank You

**Closed** 2024-08-09 17:19 UTC
Labels: gssoc
